In [2]:
text = "share prices publicly traded firms worldwide use blockchain crypto describe risen past two years imaging firm shares surged announced cryptocurrency us based long island tea shares surged nearly changed name long blockchain corp"
text

'share prices publicly traded firms worldwide use blockchain crypto describe risen past two years imaging firm shares surged announced cryptocurrency us based long island tea shares surged nearly changed name long blockchain corp'

In [5]:
from summa.summarizer import summarize

#print("headlines : ",data.iloc[0, 0])
print("extractive summarization : ", summarize(text, ratio=2.4))

extractive summarization :  


In [6]:
import urllib.request
import pandas as pd
import numpy as np
#urllib.request.urlretrieve("https://raw.githubusercontent.com/sunnysai12345/News_Summary/master/news_summary_more.csv", filename="news_summary_more.csv")
data = pd.read_csv('news_summary_more.csv', encoding='iso-8859-1')

data.sample(10)

headlines  \
59049  Hyderabad schools declare holiday over Ivanka'...   
32920  US judge orders Iran to pay $6bn to kin of 9/1...   
3262   Drugmakers not living up to commitments on pri...   
39047  I am depressed: Uncapped cricketer who won 4 a...   
4764   Cow assaulted in Andhra, police to probe if it...   
39400  Wasim Akram used wife for sexual fantasies: Im...   
75352  China issues ban on N Korean imports to implem...   
56883  If homosexuality is okay, so is paedophilia: E...   
79818  Flight delayed for 5 hours after child boards ...   
94817   Photosynthesis grew by 30% over 200 years: Study   

                                                    text  
59049  Several schools in Hyderabad declared a holida...  
32920  A US federal judge has ordered Iran to pay mor...  
3262   US President Donald Trump on Saturday took to ...  
39047  Kerala all-rounder Jalaj Saxena, who has won f...  
4764   A cow was allegedly "brutally assaulted" in An...  
39400  Pakistani cricketer-turned-politician Imran Kh...  
75352  China on Monday announced a ban on imports of ...  
56883  Former mayor of the US' Oklahoma City, Kirk Hu...  
79818  A China flight was delayed for five hours afte...  
94817  US-based researchers have estimated that net p...

In [7]:

print("headlines : ",data.iloc[0, 0])
print("extractive summarization : ", summarize(data.iloc[0, 1], ratio=0.4))

headlines :  upGrad learner switches to career in ML & Al with 90% salary hike
extractive summarization :  upGrad's Online Power Learning has powered 3 lakh+ careers.


In [8]:
data.iloc[0, 1]

"Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

In [9]:
type(text)

str

In [10]:
type(data.iloc[0, 1])

str

In [11]:
print("extractive summarization : ", summarize(text, ratio=0.4))

extractive summarization :  


In [12]:
text2 = "Saurav Kant, an alumnus of upGrad and IIIT-B's PG Program in Machine learning and Artificial Intelligence, was a Sr Systems Engineer at Infosys with almost 5 years of work experience. The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike. upGrad's Online Power Learning has powered 3 lakh+ careers."

In [19]:
print("extractive summarization : ", summarize(text2, ratio=0.7))

extractive summarization :  The program and upGrad's 360-degree career support helped him transition to a Data Scientist at Tech Mahindra with 90% salary hike.
upGrad's Online Power Learning has powered 3 lakh+ careers.


In [28]:
dims = [4096] * 7
dims

[4096, 4096, 4096, 4096, 4096, 4096, 4096]

In [46]:
import numpy as np
x = np.random.randn(16, dims[0])
x

for val in x:
    print(val.sum())

-57.35671764235842
-3.346077141092568
100.38993887974138
49.468262963963674
-21.581156437516555
15.28410947884607
65.53035405005969
78.690751325429
55.76905655885513
57.61888132748079
-17.590648585640707
19.21957789736305
-45.44934064837025
34.89211645676883
-4.266676569636983
161.45365608978756


In [22]:
dim[1:]

[4096, 4096, 4096, 4096, 4096, 4096]

In [49]:
hs = []
for din, dout in zip(dim[:-1], dim[1:]):
    print(din, dout)
    W = 0.05 * np.random.randn(din, dout)
    x = np.tanh(x.dot(W))
    for val in x:
        print(val.max(), val.min(), val.mean())
    print("------")
    hs.append(x)

4096 4096
0.999999989857666 -0.9999999529842831 -0.0033647494915343247
0.9999999921104952 -0.9999999975533637 0.004038460322891587
0.9999999852473358 -0.9999999854549809 0.02375644577311958
0.9999999978327844 -0.9999999998979676 0.011995406157669983
0.9999999999707356 -0.9999999238899043 0.005652779234219805
0.9999999982425877 -0.9999999953003007 -0.004831508799060401
0.9999998936865095 -0.9999999990345599 0.0027889693191505945
0.9999999722612596 -0.9999999686627234 -0.014353079094761459
0.9999999997580353 -0.9999999854136318 0.002989376617733002
0.9999999831536512 -0.9999999915011398 0.0024349325134866463
0.9999999957509876 -0.9999999992881128 0.007229350745513218
0.9999999874922295 -0.9999999992445294 0.004152282975596982
0.9999999995160823 -0.9999999982276252 0.02243817988667266
0.9999999935292007 -0.9999999748327707 0.015963769129190016
0.9999999997081463 -0.9999999904459904 -0.004587985836969249
0.9999999800842834 -0.9999999918864638 0.02137195180852868
------
4096 4096
0.99999999

In [52]:
hs = []
for din, dout in zip(dim[:-1], dim[1:]):
    print(din, dout)
    W = 0.05 * np.random.randn(din, dout)
    for val in x:
        val = val.dot(W)
        print(val[:5])
        print(val.max(), val.min(), val.mean())
    x = np.tanh(x.dot(W))
    print("------")
    hs.append(x)

4096 4096
[-2.55814342  1.29738967  4.1361904  -2.30908092 -1.63853196]
8.862480909364889 -10.359494291138398 0.009629142149669524
[ 7.0826064  -2.5162249   0.48671615  2.510899   -2.86276984]
9.44155715047679 -10.39491304314298 -0.028039959979030298
[-0.45153413  1.09593013 -3.05459763  1.47503273 -0.79233137]
10.06648650047568 -9.402430452738779 -0.07543789894913686
[-1.54868926  4.99297198 -2.80419956 -0.02126213  2.11343605]
10.092818944571484 -9.699324609860472 -0.0794753890060759
[-2.84680088  0.09049514 -2.57357046 -0.60807757  3.48128382]
10.81750338130992 -9.666205334408678 0.06801521419393787
[ 2.58755256  4.2668435   1.18919336 -3.83617654  0.51188723]
9.624500236282392 -9.484216894073864 0.01878392000639761
[-2.92295968 -2.73580992 -1.25300012 -2.60386225 -4.95687202]
11.053168681173174 -12.277023093501317 0.030496002596212102
[-1.4093797   0.81515339 -2.4956648   1.12741745  4.26671165]
11.038685818152729 -9.537749577300053 -0.03150370161390383
[ 4.50546588  3.62667908 -4.

[ 0.93103455 -0.85543735  2.65614125  0.33889931  1.89233259]
12.058065539090522 -9.716245654880945 0.0718928241297585
[ 0.00589681  0.39636098 -1.01082436 -5.4443541  -2.15202534]
9.646686587079623 -10.308151998704227 -0.04921090208518559
[-5.02307344  2.73755459  1.45184475 -1.94120389 -0.15937874]
9.399865911533183 -10.342937319618958 -0.05209541280242589
[-0.05718012 -2.8534025  -5.62833286 -4.3672108  -0.94013218]
10.160190557613134 -11.205080502648189 -0.04138459380177624
[-3.04134508 -3.41545451  1.50190118 -1.87698427  0.3336368 ]
10.739729158579769 -9.634982687812345 -0.07623486137998295
[ 2.69864081  0.28398626  2.60122633 -0.35281251  2.98138502]
10.36556941701355 -9.797920125787476 0.01019238989687967
[0.31823226 1.00660496 0.84502519 2.73985231 1.91830552]
9.682454319888105 -9.468156453089367 0.05787814905757554
[ 2.98152603 -2.17460485  0.0821953   3.14721468 -0.75435085]
8.405704869632107 -10.507807042203883 -0.01825369962789567
[ 3.92475384 -1.81832616 -0.5264783   2.43

In [37]:
hs[1].sum()

-109.6099475168339

In [38]:
hs[2].sum()

51.632731304164935

In [39]:
hs[3].sum()

-22.630382288795715

In [40]:
hs[4].sum()

-121.1466195803562

In [41]:
hs[5].sum()

271.42182746977466