In [1]:
import pandas as pd
import urllib.request
import matplotlib.pyplot as plt
import re
from konlpy.tag import Mecab
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from collections import Counter
from tensorflow.keras.initializers import Constant


In [2]:
vocab_size = len(word_to_index)
word_vector_dim = 100  # 워드 벡터의 차원수 (변경가능한 하이퍼파라미터)

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(None,)))
model.add(keras.layers.Conv1D(512, 14, activation='relu'))
model.add(keras.layers.MaxPooling1D(2))
model.add(keras.layers.Conv1D(512, 14, activation='relu'))
model.add(keras.layers.GlobalMaxPooling1D())
model.add(keras.layers.Dense(8, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))  # 최종 출력은 긍정/부정을 나타내는 1dim 입니다.

model.summary()

NameError: name 'word_to_index' is not defined

In [5]:
input_shape = (4, 10, 128)
x = tf.random.normal(input_shape)
y = keras.layers.Conv1D(32, 3, activation="relu")(x)
print(y.shape)

(4, 8, 32)


In [10]:
input_shape = (100, 43)
vocab_size = 10
word_vector_dim = 5
x = tf.random.normal(input_shape)
print(x)
print(x.shape)
y = keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(None,))
print(y.shape)

tf.Tensor(
[[ 6.7418545e-01 -2.8626782e-01 -2.3915540e-01 ...  1.8930699e-01
  -1.9417613e+00 -1.1867785e+00]
 [-1.9895293e-01  1.8146215e-01  8.7643528e-01 ...  4.5543870e-01
   3.3444798e-01  3.3205020e-01]
 [ 5.6640977e-01  1.1480675e+00  1.4531080e-01 ...  1.3020878e+00
   1.9847550e-03 -1.3159907e+00]
 ...
 [-1.7830979e+00  7.6262601e-02 -1.2993813e-01 ... -5.5149174e-01
  -1.7748146e+00  2.3595302e+00]
 [-5.3864878e-01  7.7050328e-01 -1.5593674e+00 ... -3.9921455e-02
  -1.0991867e+00  7.0396554e-01]
 [-1.6182830e+00 -4.2390618e-01 -5.4913646e-01 ... -8.2374012e-01
  -9.1019921e-02  1.7651708e+00]], shape=(100, 43), dtype=float32)
(100, 43)


AttributeError: 'Embedding' object has no attribute 'shape'

In [35]:
tf.keras.backend.clear_session()


model = keras.Sequential()
model.add(keras.layers.Conv1D(3, 2, activation='relu', input_shape=(None, 2)))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, None, 3)           15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [36]:
tf.keras.backend.clear_session()


model = keras.Sequential()
model.add(keras.layers.Conv1D(4, 2, activation='relu', input_shape=(None, 2)))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d (Conv1D)              (None, None, 4)           20        
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________


In [24]:
input_shape = (4, 10, 128)
x = tf.random.normal(input_shape)
y = keras.layers.Conv1D(32, 3, activation="relu")(x)
y = keras.layers.MaxPooling1D(2) (x)
print(y.shape)

(4, 5, 128)
Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_21 (Conv1D)           (None, None, 32)          4512      
Total params: 4,512
Trainable params: 4,512
Non-trainable params: 0
_________________________________________________________________


In [14]:
input_shape = (4, 43, 100)
x = tf.random.normal(input_shape)
y = keras.layers.Conv1D(512, 32, activation="relu")(x)
#y = keras.layers.MaxPooling1D(2) (x)
print(y.shape)

(4, 12, 512)


In [16]:
input_shape = (4, 43, 100)
x = tf.random.normal(input_shape)
y = keras.layers.Conv1D(512, 32, activation="relu")(x)
y = keras.layers.MaxPooling1D(7) (x)
print(y.shape)

(4, 6, 100)


In [17]:
input_shape = (4, 43, 100)
x = tf.random.normal(input_shape)
y = keras.layers.Conv1D(512, 32, activation="relu")(x)
y = keras.layers.MaxPooling1D(2) (x)
print(y.shape)

(4, 21, 100)


In [49]:
img_w, img_h = 5, 4
nums, ch = 4, 1


input_shape = (nums, img_w, img_h, ch)
x = tf.random.normal(input_shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(x)
print(y.shape)
tf.keras.backend.clear_session()


model = keras.Sequential()
model.add(keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_w, img_h, ch)))
model.summary()
print(y.shape)

(4, 3, 2, 32)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 3, 2, 32)          320       
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________
(4, 3, 2, 32)


In [54]:
img_w, img_h = 7, 6
nums, ch = 4, 1


input_shape = (nums, img_w, img_h, ch)
x = tf.random.normal(input_shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(x)
print(y.shape)
y = keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid')(y)
print(y.shape)
tf.keras.backend.clear_session()


model = keras.Sequential()
model.add(keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_w, img_h, ch)))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid'))
model.summary()

(4, 5, 4, 32)
(4, 4, 3, 32)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 5, 4, 32)          320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 4, 3, 32)          0         
Total params: 320
Trainable params: 320
Non-trainable params: 0
_________________________________________________________________


In [56]:
img_w, img_h = 7, 6
nums, ch = 4, 1


input_shape = (nums, img_w, img_h, ch)
x = tf.random.normal(input_shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(x)
print(y.shape)
y = keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid')(y)
print(y.shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(y)
print(y.shape)


tf.keras.backend.clear_session()
model = keras.Sequential()
model.add(keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(img_w, img_h, ch)))
model.add(keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid'))
model.add(keras.layers.Conv2D(16, (2,2), activation='relu'))
model.summary()

(4, 5, 4, 32)
(4, 4, 3, 32)
(4, 2, 1, 32)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 5, 4, 32)          320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 4, 3, 32)          0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 3, 2, 16)          2064      
Total params: 2,384
Trainable params: 2,384
Non-trainable params: 0
_________________________________________________________________


In [60]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
print(x.shape)
print(x)
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=2, padding='valid')
max_pool_1d(x)

(1, 5, 1)
tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[2.],
        [4.]]], dtype=float32)>

In [62]:
x = tf.constant([1., 2., 3., 4., 5.])
x = tf.reshape(x, [1, 5, 1])
print(x.shape)
print(x)
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=2, strides=1, padding='valid')
max_pool_1d(x)

(1, 5, 1)
tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]]], shape=(1, 5, 1), dtype=float32)


<tf.Tensor: shape=(1, 4, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.],
        [5.]]], dtype=float32)>

In [66]:
x = tf.constant([1., 2., 3., 4., 5., 6.])
x = tf.reshape(x, [1, 6, 1])
print(x.shape)
print(x)
max_pool_1d = tf.keras.layers.MaxPooling1D(pool_size=3, padding='valid')
max_pool_1d(x)

(1, 6, 1)
tf.Tensor(
[[[1.]
  [2.]
  [3.]
  [4.]
  [5.]
  [6.]]], shape=(1, 6, 1), dtype=float32)


<tf.Tensor: shape=(1, 2, 1), dtype=float32, numpy=
array([[[3.],
        [6.]]], dtype=float32)>

In [ ]:
nums = 50
vocab_size =  43
word_vector_dim = 100

input_shape = (nums, img_w, img_h, ch)
x = tf.random.normal(input_shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(x)
print(y.shape)
y = keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(1, 1), padding='valid')(y)
print(y.shape)
y = keras.layers.Conv2D(32, (3, 3), activation="relu")(y)
print(y.shape)

vocab_size = len(word_to_index)
word_vector_dim = 100  # 워드 벡터의 차원수 (변경가능한 하이퍼파라미터)

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(None,)))
model.add(keras.layers.Conv1D(512, 14, activation='relu'))
model.add(keras.layers.MaxPooling1D(2))
model.add(keras.layers.Conv1D(512, 14, activation='relu'))
model.add(keras.layers.GlobalMaxPooling1D())
model.add(keras.layers.Dense(8, activation='relu'))
model.add(keras.layers.Dense(1, activation='sigmoid'))  # 최종 출력은 긍정/부정을 나타내는 1dim 입니다.

model.summary()

In [69]:
tf.keras.backend.clear_session()


nums = 50
sentence_len = 43
vocab_size =  1000
word_vector_dim = 100

cnn = keras.Sequential()
cnn.add(keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(sentence_len,)))
cnn.add(keras.layers.Conv1D(16, 7, activation='relu'))
cnn.add(keras.layers.MaxPooling1D(5))
cnn.add(keras.layers.Conv1D(16, 7, activation='relu'))
cnn.add(keras.layers.GlobalMaxPooling1D())
cnn.add(keras.layers.Dense(8, activation='relu'))
cnn.add(keras.layers.Dense(1, activation='sigmoid'))  # 최종 출력은 긍정/부정을 나타내는 1dim 입니다.

cnn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 43, 100)           100000    
_________________________________________________________________
conv1d (Conv1D)              (None, 37, 16)            11216     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 7, 16)             0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 1, 16)             1808      
_________________________________________________________________
global_max_pooling1d (Global (None, 16)                0         
_________________________________________________________________
dense (Dense)                (None, 8)                 136       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 9

In [74]:

vocab_size = 100000  # 어휘 사전의 크기    ###################################이게 크기가 작으면 모델 훈련이 안 된다 왜?
word_vector_dim = 100   # 단어 하나를 표현하는 임베딩 벡터의 차원수입니다. 

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(None,)))
model.add(keras.layers.Conv1D(512, 128, activation='relu'))
model.add(keras.layers.MaxPooling1D())
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 100)         10000000  
_________________________________________________________________
conv1d_6 (Conv1D)            (None, None, 512)         6554112   
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, None, 512)         0         
Total params: 16,554,112
Trainable params: 16,554,112
Non-trainable params: 0
_________________________________________________________________


In [75]:

vocab_size = 100000  # 어휘 사전의 크기    ###################################이게 크기가 작으면 모델 훈련이 안 된다 왜?
word_vector_dim = 100   # 단어 하나를 표현하는 임베딩 벡터의 차원수입니다. 

model = keras.Sequential()
model.add(keras.layers.Embedding(vocab_size, word_vector_dim, input_shape=(None,)))
model.add(keras.layers.Conv1D(512, 128, activation='relu'))
model.add(keras.layers.MaxPooling1D())
model.add(keras.layers.Conv1D(512, 128, activation='relu'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, None, 100)         10000000  
_________________________________________________________________
conv1d_7 (Conv1D)            (None, None, 512)         6554112   
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, None, 512)         0         
_________________________________________________________________
conv1d_8 (Conv1D)            (None, None, 512)         33554944  
Total params: 50,109,056
Trainable params: 50,109,056
Non-trainable params: 0
_________________________________________________________________
